name: Actualizar EPG acontra+

on:
  schedule:
    - cron: '0 */6 * * *' # Cada 6 horas
  workflow_dispatch:      # Bot√≥n manual para probar

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install tzdata
      - run: python generador_acontra.py
      - name: Guardar cambios
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add acontra_plus.xml
          git commit -m "Actualizar EPG" || echo "Sin cambios"
          git push
